### PR TITLE
Minor fixes

### LINKED ISSUE #54: AttributeError: 'HTLetterpacerLib' object has no attribute 'factor'
Hi, this was working earlier today but, upon a Glyphs restart, it stopped working. The custom parameters for HTLetterspacer were added before that restart; perhaps they have something to do with it? Thank you.

```
Start
Config file exists
Traceback (most recent call last):
  File "HT_LetterSpacer_lib.py", line 339, in spaceMain
    lp, rp = self.setSpace(layer, referenceLayer)
  File "HT_LetterSpacer_lib.py", line 289, in setSpace
    self.newL = math.ceil(0 - distanceL + self.calculateSBValue(lPolygon))
  File "HT_LetterSpacer_lib.py", line 250, in calculateSBValue
    whiteArea = areaUPM * self.factor * 100
AttributeError: 'HTLetterpacerLib' object has no attribute 'factor'

\f_f_i\
Using master custom parameter, paramArea: 300.0
Using master custom parameter, paramDepth: 5.0
Using master custom parameter, paramOver: 20.0

End
```

### LINKED ISSUE #58: Glyphs 3: Custom Parameters have wrong format
Currently, copying parameters from Letterspacer UI results in this clipboard string:

```
(
        {
        paramArea = 430;
    },
        {
        paramDepth = 20.00;
    },
        {
        paramOver = 15;
    }
)
```

For glyphs 3, it needs to be formatted like this though:

```
{
    customParameters =     (
                {
            name = paramOver;
            value = 15;
        },
                {
            name = paramDepth;
            value = 20;
        },
                {
            name = paramArea;
            value = 400;
        }
    );
}
```

### PR DESCRIPTION
**Pull request by madig**
Maybe this helps with Glyphs 3 support. I don't have a Glyphs 3 license so I can't test it there :grimacing: 

Closes #54.
Closes #58.

@schriftgestalt you said somewhere you changed the way (sub)categorization works? That'd need changes to the default config file.

### CODE REVIEW

**Comment by jpt** [comment]
this runs in glyphs3 but doesn't space correctly unfortunately. this is similar to an issue I had when giving lefty, righty, and factor default values in the branch I was working on in #55. it also produces different results each time you run it consecutively, which is  also a problem I ran up against. happy to continue testing if you don't have access to the app

**Comment by madig** [comment]
Please to be making a test font (Glyphs 2 format or UFO) that triggers both issues.

**Comment by madig** [comment]
@jpt you still alive? Please test the latest branch state. I now decompose the layer in question up front, so none of the internal methods see a component.

**Comment by jpt** [comment]
@madig Sorry! @andrestelex already merged but I am getting the following error now:

```
Traceback (most recent call last):
  File "HT_LetterSpacer_UI.py", line 15
    HT_LetterSpacer_script.HTLetterspacerScript(ui=True)
TypeError: __init__() missing 1 required positional argument: 'drawAreas'
```

**Comment by jpt** [comment]
Disregard, not sure why that error went away but it did. Maybe had it open in an editor.

There is an issue with print vs print() but see #55 for a different issue that has yet to be solved for G3

**Pull request merged**
